# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile number')),
                ('user_type', models.CharField(choices=[('0', 'Admin'), ('1', 'General'), ('2', 'Business')], default=1, max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar_directory_path/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'innstalusers',
                'verbose_name': 'innstaluser',
            },
        ),
    ]
