# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Package Name')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Package Title')),
                ('price', models.CharField(max_length=50, verbose_name='Package Cost')),
                ('duration', models.DurationField(blank=True, default=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile number')),
                ('user_type', models.CharField(choices=[('0', 'Admin'), ('1', 'General'), ('2', 'Business')], default=1, max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar_directory_path/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
