# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_businessuserprofile_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuserprofile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
