# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180116_0831'),
        ('common', '0006_userplans'),
    ]

    operations = [
    ]
