# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_merge_20180117_0810'),
        ('common', '0007_merge_20180118_1149'),
    ]

    operations = [
    ]
