# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_merge_20180119_1143'),
        ('common', '0008_merge_20180119_1159'),
        ('common', '0008_merge_20180119_1222'),
    ]

    operations = [
    ]
