# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_merge_20180123_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
