# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_merge_20180119_1159'),
        ('common', '0009_merge_20180119_1325'),
    ]

    operations = [
    ]
