# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_auto_20180111_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
