# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_userplans'),
        ('warranty', '0003_warranty_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedWarranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default=1, max_length=200)),
                ('claimed_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.UserProfile')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warranty.Warranty')),
            ],
        ),
    ]
