# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0004_claimedwarranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimedwarranty',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
