# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0005_auto_20180116_1124'),
        ('warranty', '0004_auto_20180118_1149'),
    ]

    operations = [
    ]
