# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0007_merge_20180123_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedwarranty',
            name='claimed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_user_warranty', to='common.UserProfile'),
        ),
    ]
