# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0008_auto_20180123_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedwarranty',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
