# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0008_merge_20180122_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_user_warranty', to='common.UserProfile'),
        ),
    ]
