# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0009_claimedwarranty_is_claimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimedwarranty',
            name='status',
        ),
    ]
