# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0012_auto_20180205_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='claimed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
