# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manual_view_count',
            field=models.IntegerField(),
        ),
    ]
