# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='business',
            new_name='user',
        ),
    ]
