# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180102_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_view_count',
            field=models.IntegerField(blank=True, default=1, max_length=5),
            preserve_default=False,
        ),
    ]
